services:
  - type: web
    name: bamasaz-ai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: HF_TOKEN
        sync: false  # مقدار آن از پنل Render ست می‌شود
    autoDeploy: true
